version: '1.0'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

